

# This file was *autogenerated* from the file TestRandomConfiguration.sage
from sage.all_cmdline import *   # import sage library

_sage_const_32 = Integer(32); _sage_const_624 = Integer(624); _sage_const_100 = Integer(100); _sage_const_1 = Integer(1); _sage_const_31 = Integer(31)
from random import Random
load("./../Untwister/untwister.sage")
r1=Random()
# 32 bit Test
output=[format(r1.getrandbits(_sage_const_32 ), f"0{_sage_const_32 }b") for i in range(_sage_const_624 )]
Untwiste=Untwister(_sage_const_32 )
for i in output:
    Untwiste.submit(i)
r2=Untwiste.getRandom()
for i in range(_sage_const_100 ):
    assert r2.getrandbits(_sage_const_32 )==r1.getrandbits(_sage_const_32 )
print("Done 32 bit")
#################################################################################
r1=Random()
# 1 bit Test
output=[format(r1.getrandbits(_sage_const_1 ), f"0{_sage_const_1 }b")+"?"*_sage_const_31  for i in range(_sage_const_624 *_sage_const_32 )]
Untwiste=Untwister(_sage_const_1 )
for i in output:
    Untwiste.submit(i)
r2=Untwiste.getRandom()
for i in range(_sage_const_100 ):
    assert r2.getrandbits(_sage_const_32 )==r1.getrandbits(_sage_const_32 )
print("Done 1 bit")

